# Generated by Django 2.2.9 on 2020-01-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('context', models.TextField(max_length=300)),
                ('complete_schedule', models.BooleanField(default=False)),
            ],
        ),
    ]
